import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Resolve @/* to <root>/src/*  (mirrors tsconfig paths).
// Delegates back to esbuild so it handles extensions (.ts, .tsx, …) normally.
const atAliasPlugin = {
	name: 'at-alias',
	setup(build) {
		build.onResolve({ filter: /^@\// }, async args => {
			return build.resolve(
				'./' + args.path.slice(2),
				{ resolveDir: path.resolve(__dirname, 'src'), kind: args.kind }
			);
		});
	},
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	jsx: "automatic",
	plugins: [atAliasPlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
